"""empty message

Revision ID: ddc8b7e73cca
Revises: 
Create Date: 2023-01-11 08:20:15.857724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddc8b7e73cca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('post', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Reaction', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id_author', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id_post', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_data',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sur_name', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_reaction',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id_post', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id_user', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reaction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reaction'], ['reaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_reaction')
    op.drop_table('users_data')
    op.drop_table('posts_users')
    op.drop_table('users')
    op.drop_table('reaction')
    op.drop_table('posts')
    # ### end Alembic commands ###
